export const levelConfig = {
  safe: {
    bgGradient: "from-green-900/40 to-emerald-900/40",
    border: "border-green-500",
    badgeBg: "bg-green-600",
    badgeText: "안전",
    statusText: "대피 불필요",
    textColor: "text-green-300",
    time: null,
    building: "정상 상태입니다",
    buildingDetail: "기상해일 위험 없음",
    floor: null,
    floorBg: "bg-green-700",
    floorBorder: "border-green-500",
  },
  caution: {
    bgGradient: "from-yellow-900/50 to-amber-900/50",
    border: "border-yellow-500",
    badgeBg: "bg-yellow-600",
    badgeText: "주의",
    statusText: "상황 주시 필요",
    textColor: "text-yellow-300",
    time: "45",
    building: "인근 안전 건물",
    buildingDetail: "현재 위치에서 도보 5분 (200m)",
    floor: "2층",
    floorBg: "bg-yellow-700",
    floorBorder: "border-yellow-500",
  },
  warning: {
    bgGradient: "from-orange-900/50 to-red-900/50",
    border: "border-orange-500",
    badgeBg: "bg-orange-600",
    badgeText: "경고",
    statusText: "대피 준비 필요",
    textColor: "text-orange-300",
    time: "25",
    building: "광화문 빌딩",
    buildingDetail: "현재 위치에서 도보 4분 (180m)",
    floor: "3층",
    floorBg: "bg-orange-700",
    floorBorder: "border-orange-500",
  },
  critical: {
    bgGradient: "from-red-900/60 to-orange-900/60",
    border: "border-red-500",
    badgeBg: "bg-red-500",
    badgeText: "긴급",
    statusText: "즉시 대피 필요",
    textColor: "text-red-300",
    time: "12",
    building: "서울시청 본관",
    buildingDetail: "현재 위치에서 도보 3분 (150m)",
    floor: "3층",
    floorBg: "bg-red-600",
    floorBorder: "border-red-400",
  },
} as const;

export type AlertLevel = keyof typeof levelConfig;
